---
version: 2.1
jobs:
  tests:
    docker:
      - image: debian:buster
    steps:
      - run: apt-get update && apt-get install -y sudo
      - run:
          name: Install Debian packaging dependencies
          command: |
            sudo apt install -y python3 git rpm git-lfs

      - run:
          name: Clone the repository with LFS
          command: git clone --depth=1 -b ${CIRCLE_BRANCH} https://github.com/freedomofpress/securedrop-yum-prod
      - run:
          name: Verify the signatures of all rpm artifacts
          command: |
            cd securedrop-yum-prod
            git-lfs install
            ./scripts/check.py --verify --all

workflows:
  build-packages:
    jobs:
      - tests
